gui:
  theme:
    activeBorderColor:
      - '#CD974B'
      - bold
#     inactiveBorderColor:
#       - '#a6adc8'
#     optionsTextColor:
#       - '#89b4fa'
    selectedLineBgColor:
      - '#333333'
#     cherryPickedCommitBgColor:
#       - '#45475a'
#     cherryPickedCommitFgColor:
#       - '#b4befe'
#     unstagedChangesColor:
#       - '#f38ba8'
#     defaultFgColor:
#       - '#cdd6f4'
#     searchingActiveBorderColor:
#       - '#f9e2af'
#
